language: generic
sudo: required
services:
  - docker:

before_install:
  - docker build -t majidkhan59/multi-docker-react-test -f ./cliient/Dockerfile.dev ./client

script:
  - docker run -e CI=true majidkhan59/multi-docker-react-test npm run test

after_success:
  - docker build -t majidkhan59/multi-client ./client
  - docker build -t majidkhan59/multi-nginx ./nginx
  - docker build -t majidkhan59/multi-server ./server
  - docker build -t majidkhan59/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push majidkhan59/multi-client
  - docker push majidkhan59/multi-nginx
  - docker push majidkhan59/multi-server
  - docker push majidkhan59/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-react"
#  env: "Docker-env"
#  bucket_name: "elastickbeanstalk-us-east-1-2312"
#  on:
#   branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
